[tool.poetry]
name = "module-three-course"
version = "0.1.0"
description = ""
authors = ["Andrew Skow <skovorodnikov11@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
